import { StyleSheet } from "react-native";
import { Colors } from "../../constants/Colors";

export const createticketStyle = StyleSheet.create({
  container: {
    flexDirection: "column",
    paddingHorizontal: 20,
    paddingBottom: 40,
    backgroundColor: "#fff",
  },
  nearbyTickets: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "center",
    width: "100%",
  },
  nearbyTicketsTitle: {
    fontFamily: "Roboto-Regular",
    alignSelf: "flex-start",
    fontSize: 16,
    marginVertical: 10,
  },
  title: {
    fontFamily: "Roboto-Bold",
    alignSelf: "center",
    fontSize: 18,
    marginVertical: 10,
    color: Colors.darkBlue,
    letterSpacing: 0.5,
  },
  description: {
    color: Colors.grey,
    fontSize: 14,
    letterSpacing: 0.3,
  },
  form: {
    paddingTop: 15,
    paddingBottom: 40,
  },
  btn: {
    // backgroundColor: Colors.greenDark,
    width: "100%",
    borderRadius: 7,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    color: "white",
    elevation: 5,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  btnText: {
    fontSize: 16,
    color: "white",
    fontFamily: "Roboto-Bold",
  },
  label: {
    fontSize: 14,
    fontWeight: "500",
    color: Colors.greenDarkest,
    fontFamily: "Roboto-Regular",
    marginVertical: 10,
  },
  addPhotoWrapperLarge: {
    width: "100%",
    backgroundColor: Colors.lightGrey3,
    borderRadius: 25,
    // paddingHorizontal: 45,
    // paddingVertical: 15,
    minHeight: 200,
    justifyContent: "center",
    alignItems: "center",

    alignSelf: "center",
    elevation: 5,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  addPhotoWrapper: {
    backgroundColor: Colors.lightGrey3,
    minHeight: 100,
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    marginVertical: 20,
    alignSelf: "center",
    elevation: 5,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    borderRadius: 25,
  },
  imageLarge: {
    // height: 80,
    // aspectRatio: 1,
    flex: 1,
    width: "100%",
    borderRadius: 25,
  },
  placeholder: {
    width: "30%",
  },
  text: {
    fontSize: 17,
    textAlign: "center",
    marginVertical: 10,
    color: Colors.greenDark,
    fontFamily: "Roboto-Bold",
  },
  error: {
    fontSize: 17,
    textAlign: "center",
    marginVertical: 10,
    color: Colors.red,
    fontFamily: "Roboto-Bold",
  },
});
