import { StyleSheet } from "react-native";
import { Colors } from "../../constants/Colors";

export const createticketStyle = StyleSheet.create({
  container: {
    flexDirection: "column",
    paddingHorizontal: 10,
    paddingBottom: 50,
  },
  nearbyTickets: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "center",
    width: "100%",
  },
  nearbyTicketsTitle: {
    fontFamily: "Lato-Regular",
    alignSelf: "flex-start",
    fontSize: 16,
    marginVertical: 10,
  },
  title: {
    fontFamily: "Lato-Bold",
    alignSelf: "center",
    fontSize: 18,
    marginVertical: 10,
    color: Colors.greenDarkest,
  },
  form: {
    paddingTop: 20,
  },
  btn: {
    backgroundColor: Colors.greenDark,
    width: "100%",
    borderRadius: 7,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    color: "white",
    elevation: 5,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  btnText: {
    fontSize: 16,
    color: "white",
    fontFamily: "Lato-Bold",
  },
  label: {
    fontSize: 14,
    fontWeight: "500",
    color: Colors.greenDarkest,
    fontFamily: "Lato-Regular",
    marginVertical: 10,
  },
  addPhotoWrapperLarge: {
    width: "100%",
    backgroundColor: Colors.lightGrey,
    borderRadius: 5,
    paddingHorizontal: 45,
    paddingVertical: 15,
    alignItems: "center",
    marginBottom: 10,
    alignSelf: "center",
  },
  addPhotoWrapper: {
    backgroundColor: Colors.lightGrey,
    borderRadius: 5,
    paddingHorizontal: 55,
    paddingVertical: 15,
    alignItems: "center",
    width: "49%",
    alignSelf: "center",
  },
  imageLarge: {
    height: 100,
    width: 100,
  },
  text: {
    fontSize: 17,
    textAlign: "center",
    marginVertical: 10,
    color: Colors.greenDark,
    fontFamily: "Lato-Bold",
  },
  error: {
    fontSize: 17,
    textAlign: "center",
    marginVertical: 10,
    color: Colors.red,
    fontFamily: "Lato-Bold",
  },
});
